# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
# NUM_MASTER_NODE = 2
NUM_WORKER_NODE = 2
JUMPBOX=1
SERVER=1


# IP_NW = "192.168.5."
# JUMPBOX_IP_START = 10
# NODE_IP_START = 20
# LB_IP_START = 30

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  config.vm.box = "debian/bookworm64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Provision jumpbox Nodes
# #   (1..JUMPBOX).each do |i|
#     config.vm.define "jumpbox" do |node|
#         # Name shown in the GUI
#         node.vm.provider "virtualbox" do |vb|
#             vb.name = "kubernetes-ha-master-#{i}"
#             vb.memory = 512
#             vb.cpus = 1
#         end
#     #     node.vm.hostname = "jumpbox"
#     #     node.vm.network :private_network, ip: IP_NW + "#{JUMPBOX_IP_START + i}"
#     #     node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"

#     #     node.vm.provision "setup-hosts", :type => "shell", :path => "debian/vagrant/setup-hosts.sh" do |s|
#     #       s.args = ["enp0s8"]
#     #     end

#     #     node.vm.provision "setup-dns", type: "shell", :path => "debian/debian-dns.sh"

#     #   end
#   end


   # Provision Load Balancer Node
   config.vm.define "jumpbox" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-jb"
        vb.memory = 512
        vb.cpus = 1
    end
    # node.vm.hostname = "jumpbox"
    # node.vm.network :private_network, ip: IP_NW + "#{JUMPBOX_IP_START}"
	# node.vm.network "forwarded_port", guest: 22, host: 2710

    # node.vm.provision "setup-hosts", :type => "shell", :path => "debian/vagrant/setup-hosts.sh" do |s|
    #   s.args = ["enp0s8"]
    # node.vm.provision "setup-dns", type: "shell", :path => "debian/update-dns.sh"
  end

   # Provision Load Balancer Node
   config.vm.define "server" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-server"
        vb.memory = 2048
        vb.cpus = 1
    end
  end

  # Provision Worker Nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "node-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "kubernetes-node-#{i}"
            vb.memory = 2048
            vb.cpus = 1
        end
    end
  end
end